### ISSUE TITLE
Weird border with Lspsaga diagnostic_jump_next() and Lspsaga diagnostic_jump_prev()

### ISSUE THREAD

**Issue by limitLiu** [neanias/everforest-nvim#3]
**First of all, thank you for revamping this theme.**

## Description

When I use the current theme, there is an underline under the border. This issue does not occur when I use other themes.

## NeoVim Version

Neovim 0.9

## Platform

macOS 13.3.1

As described.

<img width="1150" alt="20230514-215357@2x" src="https://github.com/neanias/everforest-nvim/assets/18195954/4e4ba154-6436-4b1d-9974-a6b306a66433">

<img width="1150" alt="image" src="https://github.com/neanias/everforest-nvim/assets/18195954/976026b3-4b12-46cc-9a98-5e644234095a">

**Comment by neanias** [comment]
Thanks for the feedback! I've noticed this on my own setup too. Which theme is the bottom screenshot?

**Comment by limitLiu** [comment]
> Thanks for the feedback! I've noticed this on my own setup too. Which theme is the bottom screenshot?

Hello, the theme of the bottom screenshot is [catppuccin](https://github.com/catppuccin/nvim).

**Comment by neanias** [comment]
I've found what the issue is: Lspsaga uses the `Diagnostic` text highlights (`DiagnosticError`, `DiagnosticWarn`, etc.) for the border when `diagnostic.border_follow` is set to `true` (the default). In Everforest, these text highlights all have undercurls. There's 2 options, really:

1. Set `diagnostic.border_follow` to be `false` in your Lspsaga configuration, or
2. The `Diagnostic` text highlights are changed to remove the undercurl or are disconnected from the `{Error,Warning,Info,Hint}Text` highlights.

I've had a look at Catppuccin and Tokyo Night and both of them have independent `Diagnostic` highlights that don't link to other highlights, so it might be worth breaking from the main Everforest theme in this instance.

**Comment by neanias** [comment]
I've done some more reading and found the maintainers of Sonokai were also reported this problem and recommended the `diagnostic.border_follow = false` fix over changing the actual colourscheme to accommodate one plugin, which I agree with. See https://github.com/sainnhe/sonokai/issues/87 for further info.

**Comment by neanias** [comment]
Hi, as an update to this one. If you want to override the highlight groups that Lspsaga uses, you can now do so using the `on_highlights` config option!

**Comment by limitLiu** [comment]
> Hi, as an update to this one. If you want to override the highlight groups that Lspsaga uses, you can now do so using the `on_highlights` config option!

Thank u for your updates and reply.
